export const QUOTATION_INQUIRY = [
  {
    rfq_id: '00001',
    source: 'Ambala',
    destination: 'Delhi',
    distance: '350 Km',
    lorry_type: '19ft open body',
    actual_weight: '6000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '12000',
    status: 'Accepted',
  },
  {
    rfq_id: '00002',
    source: 'Gurgaon',
    destination: 'Surat',
    distance: '585 Km',
    lorry_type: '14 ft canter',
    actual_weight: '6000kg',
    mode: 'Express',
    Date: '16 Aug 2021',
    quotation: '18000',
    status: 'Rejected',
  },
  {
    rfq_id: '00003',
    source: 'Delhi',
    destination: 'Patna',
    distance: '1080 Km',
    lorry_type: '19ft open body',
    actual_weight: '6000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '25000',
    status: 'Accepted',
  },
  {
    rfq_id: '00004',
    source: 'Indore+Jabalpur',
    destination: 'Pune',
    distance: '350 Km',
    lorry_type: '32 ft DXL HQ',
    actual_weight: '8000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '60000',
    status: 'Accepted',
  },
  {
    rfq_id: '00005',
    source: 'Chennai',
    destination: 'Hyderabad',
    distance: '283 Km',
    lorry_type: '17 ft canter',
    actual_weight: '8000kg',
    mode: 'Normal',
    Date: '08 Aug 2021',
    quotation: '18000',
    status: 'Rejected',
  },
  {
    rfq_id: '00006',
    source: 'Delhi',
    destination: 'Patna',
    distance: '1080 Km',
    lorry_type: '19ft open body',
    actual_weight: '6000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '25000',
    status: 'Accepted',
  },
];
export const QUOTATION_RECEIVED = [
  {
    rfq_id: '00001',
    source: 'Ambala',
    destination: 'Delhi',
    distance: '350 Km',
    lorry_type: '19ft open body',
    actual_weight: '6000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '12000',
    status: 'Accepted',
  },
  {
    rfq_id: '00004',
    source: 'Indore+Jabalpur',
    destination: 'Pune',
    distance: '350 Km',
    lorry_type: '32 ft DXL HQ',
    actual_weight: '8000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '60000',
    status: 'Accepted',
  },
  {
    rfq_id: '00005',
    source: 'Chennai',
    destination: 'Hyderabad',
    distance: '283 Km',
    lorry_type: '17 ft canter',
    actual_weight: '8000kg',
    mode: 'Normal',
    Date: '08 Aug 2021',
    quotation: '18000',
    status: 'Rejected',
  },
];
export const STATUS = [
  {
    rfq_id: '00001',
    source: 'Ambala',
    destination: 'Delhi',
    distance: '350 Km',
    lorry_type: '19ft open body',
    actual_weight: '6000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '12000',
    target_rate: '10000',
    status: 'Accepted',
  },
  {
    rfq_id: '00004',
    source: 'Indore+Jabalpur',
    destination: 'Pune',
    distance: '350 Km',
    lorry_type: '32 ft DXL HQ',
    actual_weight: '8000kg',
    mode: 'Normal',
    Date: '19 Aug 2021',
    quotation: '60000',
    target_rate: '60000',
    status: 'Accepted',
  },
  {
    rfq_id: '00005',
    source: 'Chennai',
    destination: 'Hyderabad',
    distance: '283 Km',
    lorry_type: '17 ft canter',
    actual_weight: '8000kg',
    mode: 'Normal',
    Date: '08 Aug 2021',
    quotation: '18000',
    target_rate: '9000',
    status: 'Rejected',
  },
];
